# 必要数据及设置
bot_qq: bot_qq
host_qq: host_qq
mirai_host: http://localhost:23456
verify_key: verify_key
db_link: sqlite+aiosqlite:///data.db
web_manager_api: true
web_manager_auto_boot: true
proxy: proxy

# 路径相关
image_path:
  setu: setu
  setu18: setu18
  real: real
  real_highq: real_highq
  wallpaper: wallpaper
  sketch: sketch

# 功能相关
functions:
  tencent:
    secret_id: secret_id
    secret_key: secret_key
  saucenao_api_key: saucenao_api_key
  wolfram_alpha_key: wolfram_alpha_key
  shadiao_app_name: shadiao_app_name

# 日志相关
log_related:
  error_retention: 14
  common_retention: 7

# 数据相关
data_related:
  lolicon_image_cache: true
  network_data_cache: true
  automatic_update: false
  data_retention: true
